# Generated by Django 4.1.1 on 2022-10-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bear_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "bear_number",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("bear_name", models.TextField(blank=True, null=True, unique=True)),
                ("bear_gender", models.TextField(blank=True, null=True)),
                ("first_identified", models.IntegerField(blank=True, null=True)),
                ("bear_size", models.TextField(blank=True, null=True)),
                ("fur_description", models.TextField(blank=True, null=True)),
                ("muzzle_description", models.TextField(blank=True, null=True)),
                ("ear_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bracket_uuid", models.UUIDField(blank=True, null=True)),
                ("bracket_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_uuid", models.UUIDField(blank=True, null=True)),
                ("competition_year", models.IntegerField()),
                ("round_number", models.IntegerField(blank=True, null=True)),
                ("final_round", models.BooleanField()),
            ],
            options={
                "unique_together": {("competition_year", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winner_votes", models.IntegerField(blank=True, null=True)),
                ("runner_up_votes", models.IntegerField(blank=True, null=True)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bears.bracket",
                    ),
                ),
                (
                    "runner_up",
                    models.ForeignKey(
                        blank=True,
                        db_column="runner_up",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="runner_up",
                        to="bears.bear",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        db_column="winner",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="winner",
                        to="bears.bear",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bracket",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bears.round",
            ),
        ),
        migrations.CreateModel(
            name="BracketContestant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bracket_contestant_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "bear",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bears.bear",
                    ),
                ),
                (
                    "bracket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bears.bracket",
                    ),
                ),
            ],
            options={
                "unique_together": {("bracket", "bear")},
            },
        ),
    ]
