# Generated by Django 4.1.1 on 2022-10-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bears", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bear",
            name="bear_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="bear",
            name="bear_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bear",
            name="bear_uuid",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="bracket",
            name="bracket_uuid",
            field=models.UUIDField(),
        ),
    ]
